"""
Django settings for lumora_project project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os.path
import sys
import os
import json
from urllib import request
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

FIELD_ENCRYPTION_KEY = '9bt8394NBTGFdGEpEZyJ2vgqDfHEVJOBM1xQAh5Q2Mk='
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rsu5cgc603%0&fg@8z+yy=q&d764x$l#nolhje+de*=6isf6ih'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '.vercel.app',
    '127.0.0.1',
    'localhost',
    '*',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lumora',
    'corsheaders',
    'rest_framework',
    'background_tasks',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.RemoteUserBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lumora_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'lumora/templates/lumora/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sejwarnakul02@gmail.com'
EMAIL_HOST_PASSWORD = 'iusbcyfndcltsjdw'
WSGI_APPLICATION = 'lumora_project.wsgi.application'


# NOTE: the exact vercel.app subdomains below are a best-guess rename from
# CORS_ALLOWED_ORIGIN_REGEXES already covers ANY *.vercel.app domain, so CORS
# itself doesn't depend on getting this exact string right. CSRF_TRUSTED_ORIGINS
# has no regex equivalent in Django, so if your real Vercel project name differs
# from "lumora.vercel.app" / "admin-lumora.vercel.app", update these three lists
# to match your actual deployed domain(s) before relying on any POST from the
# deployed frontend -- otherwise Django will reject it as a CSRF failure.
CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://lumoraapp.vercel.app",
    "https://admin-lumora.vercel.app",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://lumoraapp.vercel.app",
    "https://admin-lumora.vercel.app",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://.*\.vercel\.app$',
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://lumoraapp.vercel.app",
    "https://admin-lumora.vercel.app",
]


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


# ── Database ──────────────────────────────────────────────────────────────────
DATABASE_URL = os.getenv('DATABASE_URL', '')

if DATABASE_URL:
    try:
        import dj_database_url
        db_config = dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
        )
        if 'OPTIONS' not in db_config:
            db_config['OPTIONS'] = {}
        db_config['OPTIONS'].setdefault('sslmode', 'require')
        db_config['OPTIONS'].setdefault('connect_timeout', 15)

        # Automatic IPv4 Pooler Fallback for Supabase if direct IPv6 domain is unreachable
        host = db_config.get('HOST', '')
        if host.endswith('.supabase.co') and host.startswith('db.'):
            project_ref = host.split('.')[1]
            pooler_host = "aws-0-ap-southeast-1.pooler.supabase.com"
            try:
                import socket
                socket.gethostbyname(host)
            except socket.gaierror:
                db_config['HOST'] = pooler_host
                db_config['PORT'] = 6543
                if not db_config['USER'].endswith(f".{project_ref}"):
                    db_config['USER'] = f"{db_config['USER']}.{project_ref}"

        DATABASES = {'default': db_config}
    except Exception as e:
        print("Database config fallback warning:", e)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
                'OPTIONS': {'timeout': 30},
            }
        }
else:
    # Local development — SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# MEDIA FOLDER

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

REST_FRAMEWORK = {
    # mutes the brower api
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),

    'DEFAULT_PERMISSION_CLASSES': (
        'core.api.permissions.DenyAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'lumora.authentication.BearerTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JWT_AUTH = {
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
}

LOGIN_REDIRECT_URL = '/authoring/'
LOGOUT_REDIRECT_URL = '/admin/login/'
LOGIN_URL = '/admin/login/'
