# Generated by Django 3.2.25 on 2026-09-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumora', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='blog_id',
            new_name='book_id',
        ),
        migrations.AlterModelTable(
            name='book',
            table='lumora_books',
        ),
    ]
